module.exports = {
  'define-tag-after-class-definition': require('./rules/define-tag-after-class-definition'),
  'expose-class-on-global': require('./rules/expose-class-on-global'),
  'extends-correct-class': require('./rules/extends-correct-class'),
  'file-name-matches-element': require('./rules/file-name-matches-element'),
  'no-constructor': require('./rules/no-constructor'),
  'no-customized-built-in-elements': require('./rules/no-customized-built-in-elements'),
  'no-dom-traversal-in-attributechangedcallback': require('./rules/no-dom-traversal-in-attributechangedcallback'),
  'no-dom-traversal-in-connectedcallback': require('./rules/no-dom-traversal-in-connectedcallback'),
  'no-exports-with-element': require('./rules/no-exports-with-element'),
  'no-method-prefixed-with-on': require('./rules/no-method-prefixed-with-on'),
  'no-unchecked-define': require('./rules/no-unchecked-define'),
  'one-element-per-file': require('./rules/one-element-per-file'),
  'tag-name-matches-class': require('./rules/tag-name-matches-class'),
  'valid-tag-name': require('./rules/valid-tag-name'),
}
