module.exports.builtInTagMap = {
  a: 'HTMLAnchorElement',
  abbr: 'HTMLElement',
  address: 'HTMLElement',
  area: 'HTMLAreaElement',
  article: 'HTMLElement',
  aside: 'HTMLElement',
  audio: 'HTMLAudioElement',
  b: 'HTMLElement',
  base: 'HTMLBaseElement',
  basefont: 'HTMLBaseFontElement',
  bdi: 'HTMLElement',
  bdo: 'HTMLElement',
  bgsound: 'HTMLBGSoundElement',
  blink: 'HTMLPhraseElement',
  blockquote: 'HTMLQuoteElement',
  body: 'HTMLBodyElement',
  br: 'HTMLBRElement',
  button: 'HTMLButtonElement',
  canvas: 'HTMLCanvasElement',
  caption: 'HTMLTableCaptionElement',
  cite: 'HTMLPhraseElement',
  code: 'HTMLElement',
  col: 'HTMLTableColElement',
  colgroup: 'HTMLTableColElement',
  content: 'HTMLContentElement',
  data: 'HTMLDataElement',
  datalist: 'HTMLDataListElement',
  dd: 'HTMLElement',
  del: 'HTMLModElement',
  details: 'HTMLDetailsElement',
  dfn: 'HTMLElement',
  dialog: 'HTMLDialogElement',
  dir: 'HTMLDirectoryElement',
  div: 'HTMLDivElement',
  dl: 'HTMLDListElement',
  dt: 'HTMLElement',
  em: 'HTMLElement',
  embed: 'HTMLEmbedElement',
  fieldset: 'HTMLFieldSetElement',
  figcaption: 'HTMLElement',
  figure: 'HTMLElement',
  font: 'HTMLFontElement',
  footer: 'HTMLElement',
  form: 'HTMLFormElement',
  frame: 'HTMLFrameElement',
  frameset: 'HTMLFrameSetElement',
  h1: 'HTMLHeadingElement',
  h2: 'HTMLHeadingElement',
  h3: 'HTMLHeadingElement',
  h4: 'HTMLHeadingElement',
  h5: 'HTMLHeadingElement',
  h6: 'HTMLHeadingElement',
  head: 'HTMLHeadElement',
  header: 'HTMLElement',
  hgroup: 'HTMLElement',
  hr: 'HTMLHRElement',
  html: 'HTMLHtmlElement',
  i: 'HTMLElement',
  iframe: 'HTMLIFrameElement',
  img: 'HTMLImageElement',
  index: 'HTMLIsIndexElement',
  input: 'HTMLInputElement',
  ins: 'HTMLModElement',
  kbd: 'HTMLElement',
  keygen: 'HTMLKeygenElement',
  label: 'HTMLLabelElement',
  legend: 'HTMLLegendElement',
  li: 'HTMLLIElement',
  link: 'HTMLLinkElement',
  main: 'HTMLElement',
  map: 'HTMLMapElement',
  mark: 'HTMLElement',
  marquee: 'HTMLMarqueeElement',
  menu: 'HTMLMenuElement',
  meta: 'HTMLMetaElement',
  meter: 'HTMLMeterElement',
  multicol: 'HTMLElement',
  nav: 'HTMLElement',
  nextid: 'HTMLNextIdElement',
  noscript: 'HTMLElement',
  object: 'HTMLObjectElement',
  ol: 'HTMLOListElement',
  optgroup: 'HTMLOptGroupElement',
  option: 'HTMLOptionElement',
  output: 'HTMLOutputElement',
  p: 'HTMLParagraphElement',
  param: 'HTMLParamElement',
  picture: 'HTMLPictureElement',
  pre: 'HTMLPreElement',
  progress: 'HTMLProgressElement',
  q: 'HTMLQuoteElement',
  rb: 'HTMLElement',
  rp: 'HTMLElement',
  rt: 'HTMLElement',
  ruby: 'HTMLElement',
  s: 'HTMLElement',
  samp: 'HTMLElement',
  script: 'HTMLScriptElement',
  section: 'HTMLElement',
  select: 'HTMLSelectElement',
  shadow: 'HTMLShadowElement',
  slot: 'HTMLSlotElement',
  small: 'HTMLElement',
  source: 'HTMLSourceElement',
  spacer: 'HTMLElement',
  span: 'HTMLSpanElement',
  strong: 'HTMLElement',
  style: 'HTMLStyleElement',
  summary: 'HTMLElement',
  table: 'HTMLTableElement',
  tbody: 'HTMLTableSectionElement',
  td: 'HTMLTableCellElement',
  template: 'HTMLTemplateElement',
  textarea: 'HTMLTextAreaElement',
  tfoot: 'HTMLTableSectionElement',
  th: 'HTMLTableCellElement',
  thead: 'HTMLTableSectionElement',
  time: 'HTMLTimeElement',
  title: 'HTMLTitleElement',
  tr: 'HTMLTableRowElement',
  track: 'HTMLTrackElement',
  u: 'HTMLElement',
  ul: 'HTMLUListElement',
  var: 'HTMLElement',
  video: 'HTMLVideoElement',
  wbr: 'HTMLElement',
}

module.exports.knownNamespaces = new Set([
  'primer',
  'polymer',
  'x',
  'rdf',
  'xml',
  'annotation',
  'color',
  'font',
  'missing',

  // https://www.webcomponents.org/collections
  'ct',
  'color',
  'currency',
  'smart',
  'github',
  'elementui',
  'smart',
  'github',
  'elementui',
  'progressive',
  'cpss',
  'xgd',
  'paper',
  'hy',
  'polymorph',
  'granite',
  'plastic',
  'vega',
  'catalyst',
  'Gathr',
  'fs',
  'cr',
  'mqtt',
  'simpla',
  'iron',
  'topseed',
  'awesome',
  'ts',
  'globalization',
  'super',
  's',
  'scary',
  'best',
  'paper',
  'platinum',
  'paper',
  'layout',
  'iron',
  'app',
  'data',
  'gold',
  'elements',
  'pf',
  'paperfire',
  'core',
  'nodecg',
  'titanium',
  'lrndesign',
  'lrn',
  'hax',
  'k4ng',
  'ros',
  'geo',
  'ibm',
  'google',
  'gfs',
  'geoloeg',
  'ami',
  'google',
  'medical',
  'cordova',
  'cth',
  'paper',
  'gui',
  'network',
  'dialogs',
  'layouts',

  // https://github.com/nuxodin/web-namespace-registry/
  'lume',
  'three',
  'fast',
  'a11y',
  'lrn',
  'mdl',
  'mui',
  'pure',
  'uk',
  'auro',
  'ui5',
  's',
  'ng',
  'amp',
  'spectrum',
  'sp',
  'smart',
  'hiq',
  'ibm',
  'google',
  'a',
  'tangy',
  'bs',
  'ion',
  'mwc',
  'mdc',
  'mat',
  'mv',
  'iron',
  'paper',
  'gold',
  'std',
  'aria',
  'dile',
  'lion',
])

module.exports.reservedTags = new Set([
  'annotation-xml',
  'color-profile',
  'font-face',
  'font-face-src',
  'font-face-uri',
  'font-face-format',
  'font-face-name',
  'missing-glyph',
])

// https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name
const PCENChar = [
  '(?:\\-',
  '\\.',
  '[0-9]',
  '_',
  '[a-z]',
  '\\xB7', // ·
  '[\\u00C0-\\u00D6]',
  '[\\u00D8-\\u00F6]',
  '[\\u00F8-\\u037D]',
  '[\\u037F-\\u1FFF]',
  '[\\u200C-\\u200D]',
  '[\\u203F-\\u2040]',
  '[\\u2070-\\u218F]',
  '[\\u2C00-\\u2FEF]',
  '[\\u3001-\\uD7FF]',
  '[\\uF900-\\uFDCF]',
  '[\\uFDF0-\\uFFFD]',
  '[\\uD800-\\uDB7F]',
  '[\\uDC00-\\uDFFF])',
].join('|')
module.exports.PCENChar = PCENChar
const customElementNameRegExp = new RegExp(`^[a-z]${PCENChar}*-${PCENChar}*$`)

module.exports.validTagName = name => customElementNameRegExp.test(name)
